import { build } from 'esbuild';
import { writeAppLicenses } from './licenses.mjs';
import { execFileSync } from 'node:child_process';
import { mkdir, readFile, writeFile, copyFile, rm } from 'node:fs/promises';
const out = '.build/electron';
let revision='untracked';try{revision=execFileSync('git',['rev-parse','--short','HEAD'],{encoding:'utf8'}).trim()+(execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim()?'-dirty':'');}catch{}
const buildId=`${revision}@${new Date().toISOString()}`;
const { version, name, author, license, repository } = JSON.parse(await readFile('package.json', 'utf8'));
await rm(out, {recursive:true,force:true});
await mkdir(`${out}/ui/assets`, { recursive: true });
await mkdir(`${out}/desktop`, { recursive: true });
const shared = { bundle: true, minify: true, target: ['chrome140'], format: 'iife', platform: 'browser', logLevel: 'warning', external: ['node:*','module','fs','path','url','worker_threads','os','util'], define: { 'import.meta.url': '"portable://app/assets/app.js"', __APP_VERSION__: JSON.stringify(version), __APP_BUILD__:JSON.stringify(buildId) } };
const wasm = await readFile('node_modules/@playcanvas/splat-transform/lib/webp.wasm');
const worker = await build({ ...shared, entryPoints: ['src/converter.worker.ts'], write: false, define: { ...shared.define, __CPU_WORKER_URL__: JSON.stringify("portable://app/assets/splat-worker.mjs"), __WEBP_WASM__: JSON.stringify(`data:application/wasm;base64,${wasm.toString('base64')}`) } });
await writeFile(`${out}/ui/assets/converter.js`, `window.PORTABLE_WORKER_SOURCE=${JSON.stringify(worker.outputFiles[0].text)};\n`);
await copyFile('node_modules/@playcanvas/splat-transform/dist/worker.mjs', `${out}/ui/assets/splat-worker.mjs`);
await build({ ...shared, entryPoints: ['src/app.ts'], outfile: `${out}/ui/assets/app.js` });
const html = (await readFile('src/index.html', 'utf8')).replace(/content="default-src[^\"]+"/, `content="default-src 'self'; script-src 'self' blob: 'wasm-unsafe-eval'; worker-src 'self' blob:; connect-src 'self' blob: data:; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'none'"`);
await writeFile(`${out}/ui/index.html`, html);
await copyFile('src/styles.css', `${out}/ui/assets/styles.css`);
await copyFile('assets/icons/app.png', `${out}/ui/assets/app-icon.png`);
for (const name of ['main.cjs','preload.cjs','library.cjs','paths.cjs']) await copyFile(`desktop/${name}`, `${out}/desktop/${name}`);
await build({ entryPoints: ['src/manifest.ts'], outfile: `${out}/desktop/manifest.cjs`, bundle: true, platform: 'node', format: 'cjs', target: 'node22' });
await writeFile(`${out}/package.json`, JSON.stringify({ name, productName:'Portable 3DGS Viewer', version, description:'Offline 3DGS viewer and converter', main:'desktop/main.cjs', buildId, author, license, repository }, null, 2));
await writeAppLicenses(out);
console.log(`Electron ${version}: ${out} (scene data stays outside the application)`);
